// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzK_2WldZv6cTvMp8dejtKHmV19x8kvkM',
    appId: '1:367695963414:web:c7cb8fd3eb3b9958319c37',
    messagingSenderId: '367695963414',
    projectId: 'fir-flutter-codelab-cef6e',
    authDomain: 'fir-flutter-codelab-cef6e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-cef6e.firebasestorage.app',
    measurementId: 'G-LFSL24SV3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9OG5v1N71pwcD8LqRsXME3Pw1DfRQb3o',
    appId: '1:367695963414:android:c97b1c4140a760a2319c37',
    messagingSenderId: '367695963414',
    projectId: 'fir-flutter-codelab-cef6e',
    storageBucket: 'fir-flutter-codelab-cef6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyBprdXD7ZlOzgIgx6AOKhFM-_2_-jcTQ',
    appId: '1:367695963414:ios:498582be658160b2319c37',
    messagingSenderId: '367695963414',
    projectId: 'fir-flutter-codelab-cef6e',
    storageBucket: 'fir-flutter-codelab-cef6e.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyBprdXD7ZlOzgIgx6AOKhFM-_2_-jcTQ',
    appId: '1:367695963414:ios:498582be658160b2319c37',
    messagingSenderId: '367695963414',
    projectId: 'fir-flutter-codelab-cef6e',
    storageBucket: 'fir-flutter-codelab-cef6e.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
